import { readFileSync, writeFileSync } from "node:fs";
import { CATEGORIES, categoryLabel, slugify, type Lang, type Project } from "./types.ts";

const DATA_PATH = new URL("../data/projects.json", import.meta.url);
const ROOT = new URL("../", import.meta.url);

function load(): Project[] {
  return JSON.parse(readFileSync(DATA_PATH, "utf-8")) as Project[];
}

/** Metadata suffix, e.g. "MIT · Windows · active". Omits empty fields. */
function meta(project: Project, lang: Lang): string {
  const parts: string[] = [];
  if (project.license) parts.push(project.license);
  if (project.platform && project.platform.length) parts.push(project.platform.join("/"));
  if (project.status && project.status !== "active") parts.push(project.status);
  if (!parts.length) return "";
  // In English a space reads better after the period; in Chinese the 。 already delimits.
  const separator = lang === "en-US" ? " " : "";
  return `${separator}(${parts.join(" · ")})`;
}

function render(lang: Lang): string {
  const projects = load()
    .slice()
    .sort((a, b) => a.id - b.id);

  const groups = CATEGORIES.map((c) => ({
    cat: c,
    items: projects.filter((p) => p.category === c.key),
  })).filter((g) => g.items.length > 0);

  const toc = groups
    .map((g) => `- [${categoryLabel(g.cat.key, lang)}](#${slugify(categoryLabel(g.cat.key, lang))})`)
    .join("\n");

  const sections = groups
    .map((g) => {
      const lines = [`## ${categoryLabel(g.cat.key, lang)}`, ""];
      for (const p of g.items) {
        lines.push(`- [${p.name}](${p.repository}) - ${p.description[lang].trim()}${meta(p, lang)}`);
      }
      return lines.join("\n");
    })
    .join("\n\n");

  const comment = `<!--\n  DO NOT EDIT THIS FILE.\n  Generated by \`bun run generate\` from data/projects.json.\n-->`;

  return `${comment}\n\n${toc}\n\n${sections}\n`;
}

const outZh = new URL("LIST.md", ROOT);
const outEn = new URL("LIST.en.md", ROOT);
writeFileSync(outZh, render("zh-CN"));
writeFileSync(outEn, render("en-US"));

// Auto-update the Projects count badge in READMEs.
const count = load().length;
for (const file of ["README.md", "README.en.md"]) {
  const path = new URL(file, ROOT);
  let content = "";
  try {
    content = readFileSync(path, "utf-8");
  } catch {
    continue; // README may not exist yet
  }
  const start = "<!-- PROJECTS_COUNT_START -->";
  const end = "<!-- PROJECTS_COUNT_END -->";
  const re = new RegExp(`${start}[^]*?${end}`);
  if (re.test(content)) {
    content = content.replace(re, `${start}${count}${end}`);
    writeFileSync(path, content);
  }
}
console.log(`✓ 已生成 LIST.md / LIST.en.md，并同步 Projects 计数（${count}）`);
